name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:jazzy-desktop-full
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system and ROS dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            python3-colcon-common-extensions \
            python3-rosdep \
            ros-jazzy-cv-bridge \
            ros-jazzy-image-transport \
            ros-jazzy-ament-cmake-gtest

      - name: Create workspace and copy source description
        run: |
          mkdir -p /home/ros_ws/src/descripttion
          cp -r $GITHUB_WORKSPACE/src/mobile_description /home/ros_ws/src/

      - name: Create workspace and copy source world
        run: |
          mkdir -p /home/ros_ws/src/world
          cp -r $GITHUB_WORKSPACE/src/mobile_world /home/ros_ws/src/


      - name: Build package
        run: |
          cd /home/ros_ws
          . /opt/ros/jazzy/setup.bash
          colcon build --packages-select mobile

      - name: Run tests
        run: |
          cd /home/ros_ws
          . install/setup.bash
          colcon test --packages-select mobile
          colcon test-result --verbose
